config/routes.rb
Rails.application.routes.draw do
  get 'portfolios/index'
  get 'portfolios/show'
  resources :allocations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issuer.rb
class Issuer < ApplicationRecord
    belongs_to :portfolio
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :issuers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/allocations_controller.rb
class AllocationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/issuers_controller.rb
class IssuersController < ApplicationController
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
        redirect_to user_session_path
    end

end

app/helpers/allocations_helper.rb
module AllocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issuers_helper.rb
module IssuersHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/allocations/index.html.erb
<h1> test </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allocator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary navbar-toggleable-xl">
  <a class="navbar-brand" href="#">PortAlloc</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to "Create Allocation", allocations_path, class: "nav-link "%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Portfolio Review</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Create Portfolios</a>
      </li>
    </ul>
  </div>
</nav>

    <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/portfolios/index.html.erb
<h1>Portfolios#index</h1>
<p>Find me in app/views/portfolios/index.html.erb</p>

app/views/portfolios/show.html.erb
<h1>Portfolios#show</h1>
<p>Find me in app/views/portfolios/show.html.erb</p>

app/views/welcome/index.html.erb
<%= simple_form_for @user, url: examples_input_group_path,
  wrapper: :input_group do |f| %>

  <%= f.error_notification %>

  <%= render partial: "shared/form_unused_as_hidden", locals: {
    f: f, fields: [:avatar, :birthday, :color, :fruit, :music, :language, :pill, :choises, :active, :friends, :mood, :awake, :first_kiss]
  } %>

  <%= f.input :name, prepend: "@" %>

  <%= f.input :email, prepend: "example-", append: "@gmail.com" %>

  <%= f.input :password, append: "🙊" %>

  <%= f.input :bio, prepend: "With textarea" %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>